# Generated by Django 2.2 on 2020-01-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='BillingNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=1),
        ),
    ]
