# Generated by Django 2.2 on 2020-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0002_auto_20200130_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Ouantity',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='BillingNumber',
            field=models.IntegerField(default='22', unique=True),
            preserve_default=False,
        ),
    ]
