# Generated by Django 2.2 on 2020-01-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0002_auto_20200122_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='BillingNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
