# Generated by Django 2.2 on 2020-01-08 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('AppoinmentNumber', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('Service', models.CharField(max_length=50)),
                ('Remark', models.TextField()),
                ('Note', models.BooleanField()),
                ('AppoinmentDate', models.DateField(default=None)),
                ('AppoinmentTine', models.TimeField()),
                ('ApplyDate', models.DateTimeField(auto_now_add=True)),
                ('RemarkDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Gender', models.CharField(max_length=11)),
                ('Note', models.TextField()),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=25)),
                ('Cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Note', models.TextField()),
                ('Catagories', models.ManyToManyField(to='parlour.Service')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlour.Customer')),
            ],
        ),
    ]
