# Generated by Django 2.2 on 2020-01-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Service', models.CharField(max_length=50)),
                ('Note', models.TextField()),
                ('Remark', models.BooleanField(default=False)),
                ('AppoinmentDate', models.DateField(default=None)),
                ('AppoinmentTine', models.TimeField()),
                ('ApplyDate', models.DateTimeField(auto_now_add=True)),
                ('RemarkDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
