# Generated by Django 2.2 on 2020-01-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0002_auto_20200130_0313'),
        ('parlour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='AppoinmentDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='Remark',
            field=models.CharField(choices=[('1', 'Accepted'), ('0', 'Rejected')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='appoinment',
            name='Service',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='Service',
            field=models.ManyToManyField(to='adminsection.Service'),
        ),
    ]
