# Generated by Django 2.2 on 2020-01-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='Remark',
        ),
    ]
