# Generated by Django 2.2 on 2020-01-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='AppoinmentNumber',
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='Note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='Remark',
            field=models.BooleanField(),
        ),
    ]
