# Generated by Django 2.2 on 2020-01-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0002_auto_20200113_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='Service',
            new_name='Services',
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='Remark',
            field=models.BooleanField(default=False),
        ),
    ]
