# Generated by Django 2.2 on 2020-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0002_auto_20200130_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='AppointmentNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
