# Generated by Django 2.2 on 2020-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0002_remove_appoinment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='Remark',
            field=models.CharField(choices=[('1', 'Accepted'), ('0', 'Rejected')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
