# Generated by Django 2.2 on 2020-01-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0003_auto_20200113_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='Services',
            new_name='Service',
        ),
    ]
