# Generated by Django 2.2 on 2020-01-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0003_appoinment_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='AppoinmentDate',
            field=models.DateField(blank=True),
        ),
    ]
