# Generated by Django 2.2 on 2020-01-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0004_auto_20200121_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='AppoinmentDate',
            field=models.DateField(),
        ),
    ]
