# Generated by Django 2.2 on 2020-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0005_auto_20200121_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='AppoinmentDate',
            field=models.DateField(blank=True),
        ),
    ]
