# Generated by Django 2.2 on 2020-01-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0006_auto_20200121_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='AppoinmentDate',
            field=models.DateField(null=True),
        ),
    ]
