# Generated by Django 2.2 on 2020-01-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0008_auto_20200121_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='AppoinmentDate',
            field=models.DateField(default=2015),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='AppoinmentTine',
            field=models.TimeField(default='2020-2-2'),
            preserve_default=False,
        ),
    ]
