# Generated by Django 2.2 on 2020-01-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0009_auto_20200122_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Remark',
            field=models.IntegerField(choices=[('1', 'Accepted'), ('0', 'Rejected')], max_length=1),
        ),
    ]
