# Generated by Django 2.2 on 2020-01-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0010_auto_20200124_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Remark',
            field=models.CharField(choices=[('1', 'Accepted'), ('0', 'Rejected')], max_length=1),
        ),
    ]
