# Generated by Django 2.2 on 2020-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0011_auto_20200124_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Remark',
            field=models.IntegerField(choices=[('1', 'Accepted'), ('0', 'Rejected')]),
        ),
    ]
