# Generated by Django 2.2 on 2020-01-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0013_auto_20200125_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Remark',
            field=models.CharField(choices=[('1', 'Accepted'), ('0', 'Rejected')], max_length=1),
        ),
    ]
